platform :ios, '10.3'

target 'RescueApp' do
  use_frameworks!

  # Pods for RescueApp
  pod 'CouchbaseLite-Swift-Enterprise', '~> 2.0.0'
  pod 'ReachabilitySwift'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Cartography'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'

  target 'RescueAppTests' do
    inherit! :search_paths
  end

  target 'RescueAppUITests' do
    inherit! :search_paths
  end

end
