platform :ios, '10.3'

target 'RescueApp' do
  use_frameworks!

  # Pods for RescueApp
  pod 'CouchbaseLite-Swift-Enterprise'
  pod 'ReachabilitySwift'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Cartography'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'

  target 'RescueAppTests' do
    inherit! :search_paths
    pod 'CouchbaseLite-Swift-Enterprise'
    pod 'ReachabilitySwift'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Cartography'
    pod 'Firebase/Storage'
    pod 'FirebaseUI/Storage'
  end

  target 'RescueAppUITests' do
    inherit! :search_paths
  end

end
